add_executable(nand nand.cpp xrt_regread.cpp)
find_package(Threads REQUIRED)
include_directories(/opt/xilinx/xrt/include)
link_directories(/opt/xilinx/xrt/lib)
target_link_libraries(nand PRIVATE tfhe++ /opt/xilinx/xrt/lib/libxrt_coreutil.so rt Threads::Threads )
file(COPY ../emconfig.json DESTINATION .)
file(COPY ../xrt.ini DESTINATION .)
